
stages: 
  - prepare
  - pom
  - release
  - deploy
prepare: 
  stage: prepare
  script:
    - mvn clean
    - mvn install

#pom: 
  #stage: pom
  #script: 
    #- sudo nano 
    #- project.version + 0.1

release:
  stage: release
  script: 
    - git config --global user.email valeria.pelzers@devoteam.com
    - git config --global user.name root
    - mvn -B release:clean release:prepare release:perform -Dusername=root -Dpassword=gitlab2022

deploy:
  stage: deploy
  script: 
    - mvn deploy
